### ISSUE TITLE
Getting secrets from the passphrase

### ISSUE THREAD

**Issue by Natim** [mozilla-services/hoverpad#23]
In hoverpad we only have the passphrase as the user secret but we need to keep it on the client side only.

From this passphrase we want to generate:

- A BasicAuth password
- A salt for the collection ID name
- An base encryption key for our records.

Here is the algorithm I suggest we use for that:

```python
keyInfo = 'identity.mozilla.com/picl/v1/hoverpad'
keyMaterial = HKDF(passphrase, "", keyInfo, 32*3)
basic_auth_key = codecs.encode(keyMaterial[:32], "hex_codec")
collection_id_salt = codecs.encode(keyMaterial[32:64], "hex_codec")
encryption_base_passphrase = codecs.encode(keyMaterial[64:96], "hex_codec")
```

**Comment by Natim** [comment]
@rfk can you tell us if this seems like a good idea?

The `encryption_base_passphrase` will be derivated with a random salt generated for each encryption (salt stored in the record along with the IV and encrypted record).

**Comment by Natim** [comment]
Maybe we can use `PBKDF2` instead of `HKDF` so that we can use `WebCrypto` to generate the keys.
We can then use `PBKDF2` with 1000, 2000 and 3000 iterations to grab the three different keys.

**Comment by rfk** [comment]
> Maybe we can use PBKDF2 instead of HKDF 

PBKDF2 and HKDF are very different things that unfortunately happen to look similar, and you'll probably want to use both here:

* PBKDF2, like bcrypt and scrypt and friends, is designed to turn a weak brute-forceable password into something that's harder to brute-force.  It's purposely designed to be slow.
* HKDF is designed to take a short good-quality key, and expand it into an arbitrary amount of good-quality key material.  It's fast, so using it on a passphrase does nothing to prevent brute-force attacks.

So I'd suggest a scheme that's similar to the one in FxA:

```
keyMaterial = PBKDF2(passphrase)  // or scrypt or whatever if you can get it
authKey = HKDF(keyMaterial, "", "identity.mozilla.com/picl/v1/hoverpad/auth", 32)
collectionKeyMaterial = HKDF(keyMaterial, "", "identity.mozilla.com/picl/v1/hoverpad/collection/" + collection_name, 2 * 32)
collectionSalt = collectionKeyMaterial[:32]
collectionKey = collectionKeyMaterial[32:]
```

We should also loop in some of the platform crypto exports for input here, before shipping this crypto to release users.

**Comment by glasserc** [comment]
What's the value of having a salt, here?

In storage.sync, we use a salt to obfuscate the collection name (so that users don't leak information about what extensions they have installed) and record IDs (so that users don't leak information about what those extensions have stored).

As for us, if I understand correctly, we only have one record in hoverpad, so I don't expect its name/ID to have any significant information. And because hoverpad doesn't integrate with chrome.storage.sync, it will already be relatively obvious to an attacker that a user has hoverpad is installed. You don't even really need access to the DB; I bet a network administrator could deduce it based on the pattern of requests and the implied sync patterns.
